# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RaceGame 1.0' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


pod 'SwiftLint'
  # Pods for RaceGame 1.0



  target 'RaceGame 1.0Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RaceGame 1.0UITests' do
    # Pods for testing
  end

end
